M48
; DRILL file {KiCad 9.0.0} date 2025-03-30T15:54:23+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-30T15:54:23+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X104.6Y-46.04
X110.38Y-46.04
T2
X80.0Y-42.0
X80.0Y-129.0
X122.0Y-42.0
X122.0Y-129.0
M30
